// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/Ephrem-shimels/A2SV_Go_Backend/task_management_with_cleanArchitecture/Domain/dtos"
	"github.com/Ephrem-shimels/A2SV_Go_Backend/task_management_with_cleanArchitecture/Domain"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindUser provides a mock function with given fields: c, registerDto
func (_m *UserRepository) FindUser(c context.Context, registerDto dtos.RegisterDto) (*domain.User, error) {
	ret := _m.Called(c, registerDto)

	if len(ret) == 0 {
		panic("no return value specified for FindUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RegisterDto) (*domain.User, error)); ok {
		return rf(c, registerDto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RegisterDto) *domain.User); ok {
		r0 = rf(c, registerDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.RegisterDto) error); ok {
		r1 = rf(c, registerDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PromoteUser provides a mock function with given fields: c, promoteDto
func (_m *UserRepository) PromoteUser(c context.Context, promoteDto dtos.PromoteDto) error {
	ret := _m.Called(c, promoteDto)

	if len(ret) == 0 {
		panic("no return value specified for PromoteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.PromoteDto) error); ok {
		r0 = rf(c, promoteDto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterUser provides a mock function with given fields: c, registerDto, hashPassword
func (_m *UserRepository) RegisterUser(c context.Context, registerDto dtos.RegisterDto, hashPassword string) (*domain.User, error) {
	ret := _m.Called(c, registerDto, hashPassword)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RegisterDto, string) (*domain.User, error)); ok {
		return rf(c, registerDto, hashPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RegisterDto, string) *domain.User); ok {
		r0 = rf(c, registerDto, hashPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.RegisterDto, string) error); ok {
		r1 = rf(c, registerDto, hashPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
